name: Save Prometheus Image

on:
  workflow_dispatch:

jobs:
  save-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Pull Prometheus Image
      run: docker pull --platform linux/arm64 prom/prometheus:v2.37.0

    - name: Save Prometheus Image as tar
      run: docker save prom/prometheus:v2.37.0 -o prometheus-arm64.tar

    - name: Upload tar file as artifact
      uses: actions/upload-artifact@v3
      with:
        name: prometheus-arm64
        path: prometheus-arm64.tar
